### ISSUE TITLE
PocNtfsFlushAndPurgeCache 

### ISSUE THREAD

**Issue by gzxzb** [hkx3upper/FOKS-TROT#11]
FileFuncs.c->PocNtfsFlushAndPurgeCache 只对NTFS有效，针对其它文件系统有什么思路可用？

**Comment by gzxzb** [comment]
调用 FltPerformSynchronousIo(Data);后，是不是要调用FltFreeCallbackData来释放Data ？


   FltPerformSynchronousIo(Data);

    FltFreeCallbackData(Data);

    return Data->IoStatus.Status;

**Comment by hkx3upper** [comment]
是的，需要FltFreeCallbackData(Data);，我会在新版本里加上的，谢谢。
其实这个函数在其他文件系统里是可以用的，但是在ntfs中可以设置MinorFunction为IRP_MN_FLUSH_AND_PURGE，可以清掉原始的缓冲。这个函数本身没大有作用，只是为了防止驱动开启之前打开过文件，已经建立了文件的缓冲（密文）。导致驱动启动之后，明文缓冲里还是之前的密文。
而像fastfat里根本不支持MinorFunction。不过你可以直接调用CcPurgeCacheSection之类的函数嘛，就是得注意Header中的那两个锁的正确获取。可以参考一下fastfat。
