### ISSUE TITLE
StartingVbo是否会溢出

### ISSUE THREAD

**Issue by wangzhankun** [hkx3upper/FOKS-TROT#14]
我在测试时拷贝了一个2G大小的文件，观察发现StartingVbo增长得很快。检查代码发现，StartingVbo是ULONG类型，那么当文件超过4G时，是会发生溢出吧？
```cpp
typedef struct _POC_PAGE_TEMP_BUFFER
{
    ULONG StartingVbo;
    ULONG ByteCount;
    PCHAR Buffer;

}POC_PAGE_TEMP_BUFFER, * PPOC_PAGE_TEMP_BUFFER;
```

**Comment by hkx3upper** [comment]
确实，当时照着fastfat搞得

**Comment by wangzhankun** [comment]
我在我那边的仓库建立了一个名为`support_greater_4G_file`的分支，希望源仓库也能建立这个分支，测试性研究对超过4G的大文件的支持。我在新分支上将大部分能修改为`LONGLONG`类型的变量都先修改成了`LONGLONG`类型。希望一起做测试研究。

**Comment by hkx3upper** [comment]
我接下来也不知道会不会再做这个方向了，你那边维护一个独立的分支就可以了，祝好.

**Comment by hkx3upper** [comment]
此问题已解决，见[1.0.0.2265](https://github.com/hkx3upper/FOKS-TROT/releases/tag/1.0.0.2265)
