### ISSUE TITLE
PAGED_CODE中断 

### ISSUE THREAD

**Issue by wangzhankun** [hkx3upper/FOKS-TROT#18]
驱动在运行到`PocPostReadOperation`时，会跳入到`PAGED_CODE`引发中断，导致系统崩溃。请问这个原因是什么呢？该如何解决呢？

**Comment by hkx3upper** [comment]
原因是PostRead的中断级别太高了，超过APC_LEVEL了，在这种中断级别下不能使用分页内存，所以有些函数不能使用。PAGED_CODE是个断言，防止中断级别太高进入我们的驱动中，
我也不知道怎么解决......

**Comment by wangzhankun** [comment]
还有个问题比较奇怪，那理论上不应该是先执行PreRead的代码，之后再执行PostRead的代码吗？为啥不会在PreRead里面引发中断呢？

**Comment by hkx3upper** [comment]
和Pre没关系，Pre是IO管理器到文件系统驱动，Post是文件系统驱动回IO管理器，书上说
Post回调函数（PFLT_POST_OPERATION_CALLBACK）
这个回调函数执行的中断等级为IRQL <= DISPATCH_LEVEL。所以需要注意以下几点：1、不能安全调用必须低于IRQL级别的任何内核模式的派遣函数。2、在这个函数内开辟的任何数据结构必须位于非页内存。3、该函数不可分页。4、不能请求资源(resource)、信号量(mutextes)和快速信号量（fast mutexes)，只能获取互斥锁（spin lock)。5、不能获取、设置或者删除上下文，但可以释放上下文。
当IRQL==DISPATCH_LEVEL时，PAGED_CODE断言就会触发

**Comment by wangzhankun** [comment]
请问您提到的这本书是什么书呀？我想参考一下。另外，那是不是意味着，我需要把PostRead改写成NonPagedCode模式呢？

**Comment by hkx3upper** [comment]
忘了，不过微软官方的文档里有
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nc-fltkernel-pflt_post_operation_callback
不用吧，如果实在想在Dispath level执行低级别的代码，好像可以用Dpc routines的Workitem，类似这个https://blog.csdn.net/weixin_30346033/article/details/95622077

**Comment by wangzhankun** [comment]
PostRead函数应该是在APC_LEVEL下运行的吧？我看`PAGED_CODE()`的宏定义就是`PAGED_ASSERT(KeGetCurrentIrql() <= APC_LEVEL)`。另外运行在APC_LEVEL模式下如果去执行PASSIVE_LEVEL的函数的话是必须要用DPC吗？我看`ZwQuerySymbolicLinkObject`函数的说明就是运行在PASSIVE_LEVEL下，但是`PocQuerySymbolicLink`函数似乎并没有做特殊处理。尽管我再TARGET MACHINE上面开启了verifier之后发现，在调用`ZwQuerySymbolicLinkObject`之后，在将返回值赋值到`Status`时确实发生了错误，对应的指令是`mov [esp+xxxx] eax`。但是，在调用`ZwQuerySymbolicLinkObject`之前，会调用同样是PASSIVE_LEVEL的`ZwOpenSymbolicLinkObject`函数确没有发生类似的错误。

**Comment by wangzhankun** [comment]
该问题在[wangzhankun/FOKS-TROT](https://github.com/wangzhankun/FOKS-TROT)的7ba92fc59a290c9cc8742b6d732aff39c30ce1aa提交上被解决。由于我的仓库已经转向C++开发，改动过多，不再合并。

**Comment by wangzhankun** [comment]
实现参见Read.cpp

**Comment by wangzhankun** [comment]
DPC已添加进来
