### ISSUE TITLE
FltLockUserBuffer ERROR

### ISSUE THREAD

**Issue by wangzhankun** [hkx3upper/FOKS-TROT#19]
实验环境：
* Windows自带的视频播放器（非机密进程）
* 加密后的mp4文件

在使用自带视频播放器尝试打开mp4文件时，PostRead函数的FltLockUserBuffer函数报错。主要信息如下：
```bash
INVALID_PROCESS_ATTACH_ATTEMPT (5)
Arguments:
Arg1: ffffcf8fa3b71080
Arg2: ffffcf8fa0618300
Arg3: 0000000000000000
Arg4: 0000000000000001

Debugging Details:
------------------


KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.Sec
    Value: 3

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on LAPTOP-MR01PTCV

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 215

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 74

    Key  : Analysis.System
    Value: CreateObject


BUGCHECK_CODE:  5

BUGCHECK_P1: ffffcf8fa3b71080

BUGCHECK_P2: ffffcf8fa0618300

BUGCHECK_P3: 0

BUGCHECK_P4: 1

PROCESS_NAME:  svchost.exe

DPC_STACK_BASE:  FFFF810BCC430FB0

```

**Comment by wangzhankun** [comment]
关于PostRead函数第309行至364行有些疑问。309至328行的代码似乎与336行至364行的代码并没有什么区别。只是后者多了`PAGED_CODE()`和`FltLockUserBuffer`函数。在执行第351行时，很明显`Data->Iopb->Parameters.Read.MdlAddress == NULL`是成立的。请问这里的区别是什么呢？既然`MdlAddress`确认是NULL了，为啥还要尝试进行内存映射呢？

**Comment by hkx3upper** [comment]
这里我没写完，你看一下https://github.com/microsoft/Windows-driver-samples/tree/master/filesys/miniFilter/swapBuffers，这里应该单独写一下的PostReadWhenSafe

**Comment by hkx3upper** [comment]
看一下Windows内核情景分析的第九章9.12 MDL，这里Read有可能是使用的UserBuffer，UserBuffer是一个进程的虚拟内存空间，因为不知道当前进程是不是UserBuffer的进程，所以不能直接使用。

**Comment by wangzhankun** [comment]
同#18
