### ISSUE TITLE
PocPreReadOperation逻辑问题

### ISSUE THREAD

**Issue by wangzhankun** [hkx3upper/FOKS-TROT#20]
`Read.c`文件第192至195行的代码逻辑似乎有些问题。当前运行的情况是当且仅当124行、135行、145行的`if`判断都为`false`时，该代码段才会执行，这是否符合原本设计意图呢？假设，`192至195行`的代码成功执行了，那就表示135行的判断为false，那么，`192行至195行`的代码就永远不应该执行（如果被执行了，那么就与`135行至142`行的逻辑相互冲突。），但是事实上它是有可能被执行到的。请问正确的执行逻辑应该是什么样的呢？

**Comment by wangzhankun** [comment]
请问Read.c中第135行为啥`if (FltObjects->FileObject->SectionObjectPointer == StreamContext->ShadowSectionObjectPointers)`成立的话就要直接转到`EXIT`呢？

**Comment by hkx3upper** [comment]
如果相等说明是密文缓冲，不解密，直接结束

**Comment by wangzhankun** [comment]
> 如果相等说明是密文缓冲，不解密，直接结束

但是为啥不直接把返回值设置成`FLT_PREOP_SUCCESS_NO_CALLBACK`然后goto到ERROR呢？为啥还要转到PostRead呢？

**Comment by hkx3upper** [comment]
为了隐藏文件标识尾......

**Comment by wangzhankun** [comment]
我不太理解您的意思。在PostRead中
![image](https://user-images.githubusercontent.com/35724924/168274152-49731ba6-21e0-4b22-94ae-f37d1cb70585.png)
这里似乎并没有对`if (FltObjects->FileObject->SectionObjectPointer == StreamContext->ShadowSectionObjectPointers)`成立做任何特殊处理呀？

**Comment by hkx3upper** [comment]
这块代码前面的
if (STATUS_SUCCESS == Data->IoStatus.Status)
    {
        if (StartingVbo + Data->IoStatus.Information > FileSize)
        {
            Data->IoStatus.Information = FileSize - StartingVbo;
        }
    }
    else if (!NT_SUCCESS(Data->IoStatus.Status) || (Data->IoStatus.Information == 0))
    {
        Status = FLT_POSTOP_FINISHED_PROCESSING;
        goto EXIT;
    }
是隐藏文件标识尾
