### ISSUE TITLE
FileObject、POC_STREAM_CONTEXT、SECTION_OBJECT_POINTERS之间的对应关系

### ISSUE THREAD

**Issue by wangzhankun** [hkx3upper/FOKS-TROT#22]
根据[SECTION_OBJECT_POINTERS structure](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_section_object_pointers)所述:
> There is a one-to-one relationship between a SECTION_OBJECT_POINTERS structure and a file stream. Multiple file objects can be associated with a particular file stream, each representing an open instance of the stream. However, only one SECTION_OBJECT_POINTERS structure can be associated with a given stream. If there are multiple file objects for a stream, the SectionObjectPointer member for all file objects must point to the same SECTION_OBJECT_POINTERS structure (that is associated with the stream).

FileObject与file stream是多对一的关系，而file stream与SECTION_OBJECT_POINTERS structure是一对一的关系。因此，对于同一份文件而言，可以有多个进程打开从而产生多个FileObject，但是该文件对应的SECTION_OBJECT_POINTERS只有一个，因此是多对一的关系。

但是在代码实现中，我们为了区分明文和密文缓冲，将`OriginSectionObjectPointers`供机密进程使用提供明文缓冲，`ShadowSectionObjectPointers`供机密进程使用提供密文缓冲。但是这两个结构体是统一封装在`POC_STREAM_CONTEXT`中的。

因此我的问题是**设计实现中的FileObject和POC_STREAM_CONTEXT**也是多对一的关系吗？

我看在代码中是通过`FltGetStreamContext`来获取`POC_STREAM_CONTEXT`的地址的，请问假设是第二次打开同一个文件，那么在此之前我们已经为同一个文件创建了`POC_STREAM_CONTEXT`，那么此时调用`FltGetStreamContext`是不是能够获取到同一个`POC_STREAM_CONTEXT`呢？也即是FileObject和POC_STREAM_CONTEXT也是多对一的关系，POC_STREAM_CONTEXT和file stream是一对一的关系。

请问我的理解是否正确呢？

**Comment by hkx3upper** [comment]
Streamcontext就相当于fcb，与fileobject是一对多的关系。
FltGetStreamContext去看看官方的文档吧，里面很清楚
