### ISSUE TITLE
NonCachedIo和CachedIo在双缓冲读时的区别

### ISSUE THREAD

**Issue by wangzhankun** [hkx3upper/FOKS-TROT#23]
请问`Read.c`的112行和145行区分是否为缓冲IO的目的是什么呀？我看微软给出的swappedBuffer的样例里面并没有对IO是否为缓冲IO有特殊的处理。只是在对非缓冲IO需要读取的字节数做了特殊判断使其至少为一个sector的大小。

**Comment by hkx3upper** [comment]
![image](https://user-images.githubusercontent.com/41336794/168259302-f74f95b4-2276-4cc5-8c83-e51212528cee.png)
加密解密都只针对非缓冲读写，而在Read中对缓冲读写处理主要是为了隐藏文件标识尾，开发文档里应该有更详细的说明。

**Comment by wangzhankun** [comment]
但是在112行的判断那里，我觉得主要逻辑是要修改Parameter.Read.Length的大小吧？这里是不是无论是否为缓冲IO都要对`StartingVbo + len_read > StreamContext->FileSize`的情况下进行修改呢？

**Comment by hkx3upper** [comment]
贴一下代码吧，我这里112行跟你的不一样......

**Comment by wangzhankun** [comment]
就是这里
![image](https://user-images.githubusercontent.com/35724924/168278175-c08061fa-ade1-4962-9735-aa0d6fdd07ba.png)

**Comment by wangzhankun** [comment]
另外这里的ByteConut是不是也要修改成StreamContext->FileSize - StartingVbo呢？

**Comment by wangzhankun** [comment]
在这里StreamContext->FileSize的值应该是已经减掉最后的加密文件标识尾的大小了吧？如果说无论是否是缓冲IO，我们都对Data->Iopb->Parameters.Read.Length进行修改，那么最多也就只能读入StreamContext->FileSize大小的字节，换言之一定不会将加密文件标识尾读入，那就不需要在PostRead中进行隐藏文件标识尾的操作了吧？

**Comment by hkx3upper** [comment]
ByteCount是个局部变量，不用修改。
![image](https://user-images.githubusercontent.com/41336794/168281804-af6696bf-7c1e-4f98-ad60-45d9a78ee2fa.png)
这是加密标识尾的格式，因为非缓冲IO是要求扇区对齐的，你在非缓冲IO修改Read.Length，就没法扇区对齐了，下面的文件系统驱动还是按照扇区对齐读的，0x1E9这块会暴露。

**Comment by wangzhankun** [comment]
我看开发文档中的描述，写入的时候是将扇区对齐之后再将标识尾部写入的吧？
![image](https://user-images.githubusercontent.com/35724924/168283428-937eaff9-d73c-4edf-bbbc-8ccc94a5384f.png)
