### ISSUE TITLE
PreWrite 写入前加密

### ISSUE THREAD

**Issue by wangzhankun** [hkx3upper/FOKS-TROT#25]
在写入之前，会对缓冲区中的数据进行加密。根据设计，如果FileSize<AES_BLOCK_SIZE则采用流式加密，如果是最后一个块的大小不足AES_BLOCK_SIZE则会采用Steal的方式。

我的问题是，假设用户写入了10个字节，并通过刷新缓冲区的方式写入硬盘，此时FileSize是小于AES_BLOCK_SIZE的，但是过了一段时间之后，用户一次性写入10MB的数据。那么在解密的时候会不会出现问题呢？

**Comment by wangzhankun** [comment]
如果确实存在所述问题的话，我想到了一种解决方案，不知可行不。

可能的解决方案是，在StreamContext里面维护一个`AES_BLOCK_SIZE`大小的缓冲区。每次写入之前都先检查该缓冲区中是否有待写入的数据，如果没有待写入的数据，则执行Write操作。如果有待写入的数据，那么就从当前待写入的数据中提取出若干数据使其能够凑足`AES_BLOCK_SIZE`,然后对其加密，写入到交换缓冲区中。剩下的数据执行其它的写入操作。在写入时，如果发现数据不足一个`AES_BLOCK_SIZE`大小，那就先将其暂存到StreamContext中，等待下次写入。

在文件执行Close之前，也即是在PreClose操作中，首先检查StreamContext是否有待写入的数据。如果有，那就按照最开始的写入设计方案写入数据即可。

**Comment by hkx3upper** [comment]
这里确实有问题，不过在这个场景下还是可以的，因为正常的应用程序都是把所有数据读出来，然后展示在界面中，最后将修改过的数据一下子写入磁盘中。
不过我昨天修复了一下，16个字节以内直接扩展文件大小到16个字节，直接使用块密码算法加密了

**Comment by wangzhankun** [comment]
我根据 #26 粘贴的测试用例进行测试发现，似乎并没有出现我提到的这种情况。再每次写入时我发现StartVbo始终都是0.有可能是我flush的数据太少，所以每次都会从0开始重新刷入硬盘，也有可能是进入到了硬盘的缓冲区中，没有实际写入。可能情况比较多，之后我再详细测试一下。

**Comment by hkx3upper** [comment]
你这个测试程序是不会导致这个问题的，这肯定是缓冲写操作，非缓冲得用Createfile带FILE_FLAG_NO_BUFFERING

**Comment by hkx3upper** [comment]
测试这种情况的话，可以先直接用记事本写入偏移0，大小0x7的数据，然后用自己的测试程序**非缓冲**写入偏移0x200，大小0x120（随便），这样前面的一块原本使用的是流密码的话，那么就出现问题了。
再者说，密文挪用这种方法本身也会出现问题，如果前面一段的数据不对齐，使用密文挪用加密了，之后又**直接**写入一段数据，那么前面的密文挪用也无法正常解密了。
所以这里我考虑的情况还只是应用程序把所有的数据读出，然后修改，再整体写入，这样就没问题了

**Comment by wangzhankun** [comment]
## 环境
* 测试文件：机密文件夹下新写入的机密后殖民的txt文档
* 写入进程：机密进程

## bug说明
目前存在的bug如图所示，每次都无缓冲的写入字符串`L"1\n"`，发现在第二次写入的时候会出现被填充了0.

应该是因为在读取的时候，读出了16字节，但是这个16字节是写入的时候padding写入的，因此第二次写入的时候误写了进去。

<img width="174" alt="image" src="https://user-images.githubusercontent.com/35724924/175804365-3ea69a19-550b-454c-af84-222c73991ad6.png">

## 测试程序
```cpp
#include <Windows.h>
#include <cstdio>
using namespace std;
int main(int argc, char const* argv[])
{
	// CreateFile 共享打开文件
	HANDLE hFile = CreateFileW(
		L"C:\\Users\\wangzhankun\\Desktop\\testdata\\hello.txt",
		//L"C:\\Users\\wangzhankun\\Desktop\\123src\\hello.txt",
		GENERIC_WRITE,
		FILE_SHARE_READ,
		NULL,
		OPEN_ALWAYS,
		FILE_FLAG_WRITE_THROUGH,
		NULL);

	// 判断文件是否打开成功
	if (hFile == INVALID_HANDLE_VALUE)
	{
		printf("CreateFile failed with error %d\n", GetLastError());
		goto EXIT;
	}

	// ReadFile 读取文件 
	for (int i = 0; i < 30; i++)
	{

		DWORD dwBytesWrite = 0;
		WCHAR szBuffer[100] = { L"1\n" };
		BOOL bWrite = WriteFile(hFile, szBuffer, wcslen(szBuffer) * sizeof(WCHAR), &dwBytesWrite, NULL);
		if (bWrite == FALSE)
		{
			printf("WriteFile failed with error %d\n", GetLastError());
			goto EXIT;
		}


		printf("%dth\n", i);
		Sleep(1000); // 每隔1秒读取一次
	}

EXIT:
	// CloseHandle 关闭文件
	if (hFile != INVALID_HANDLE_VALUE)
		CloseHandle(hFile);

	system("pause");

	return 0;
}

```

**Comment by wangzhankun** [comment]
> 测试这种情况的话，可以先直接用记事本写入偏移0，大小0x7的数据，然后用自己的测试程序**非缓冲**写入偏移0x200，大小0x120（随便），这样前面的一块原本使用的是流密码的话，那么就出现问题了。 再者说，密文挪用这种方法本身也会出现问题，如果前面一段的数据不对齐，使用密文挪用加密了，之后又**直接**写入一段数据，那么前面的密文挪用也无法正常解密了。 所以这里我考虑的情况还只是应用程序把所有的数据读出，然后修改，再整体写入，这样就没问题了

请问你这边说把数据都读出了，代码是在哪里呀？我在Write.c中好像没有找到相关的代码哎。

**Comment by wangzhankun** [comment]
在`PostWrite`中：
```cpp
    if (BooleanFlagOn(Data->Iopb->IrpFlags, IRP_NOCACHE) &&
        TRUE != StreamContext->LessThanAesBlockSize)
    {
        /*
        * 记录文件的明文大小，小于16个字节的StreamContext->FileSize已经在其他处更新过了，
        * 这里不能再更新了，因为这里的FileSize已经是16个字节了。
        */
        ExEnterCriticalRegionAndAcquireResourceExclusive(StreamContext->Resource);

        StreamContext->FileSize = ((PFSRTL_ADVANCED_FCB_HEADER)FltObjects->FileObject->FsContext)->FileSize.QuadPart;

        ExReleaseResourceAndLeaveCriticalRegion(StreamContext->Resource);
    }
```
注释说是`小于16个字节的StreamContext->FileSize已经在其他处更新过了`，但是我没有在代码中找到哎。这个应该就是在前两次写入的时候多写入的原因吧？是因为忘了处理了吗？

**Comment by wangzhankun** [comment]
## 执行顺序
我发现NonCachedIO和CachedIo在Post执行上有些反直觉。应用程序在指定了`FILE_FLAG_WRITE_THROUGH`时，一次Write过程时这样的：
1. PreWrite    CachedIO
2. PreWrite    NonCachedIO
3. PostWrite   NonCachedIO
4. PostWrite   CachedIO

这四步的过程有些反直觉。直觉上应该是执行完PreWrite的CachedIO之后应该立即执行CachedIo的PostWrite才是，但是实际过程与此相反。直觉是，应该是限制性CachedIO的PostWrite再执行NonCachedIO的PostWrite，但是实际上也与此相反。

## 写入长度还原
在针对`FileSize<AES_BLOCK_SIZE`的文件大小上有做一次还原的操作，
```cpp
    if (!NonCachedIo)
    {
        /*
        * 16个字节以内扩展文件大小，还有一处在PreSetInfo，按道理应该是if (!PagingIo)，但
        * NonCachedIo要求Length > SectorSize，所以if (!NonCachedIo)就行。
        */

        if (FileSize < AES_BLOCK_SIZE)
        {
            /*
            * FSD的Write会帮我们扩展文件大小，可以在FastFat的Write中搜索ExtendingFile
            */
            if (StartingVbo + Data->Iopb->Parameters.Write.Length < AES_BLOCK_SIZE)
            {
                SwapBufferContext->OriginalLength = Data->Iopb->Parameters.Write.Length;

                ExEnterCriticalRegionAndAcquireResourceExclusive(StreamContext->Resource);

                StreamContext->FileSize = StartingVbo + Data->Iopb->Parameters.Write.Length;
                StreamContext->LessThanAesBlockSize = TRUE;

                ExReleaseResourceAndLeaveCriticalRegion(StreamContext->Resource);

                Data->Iopb->Parameters.Write.Length = AES_BLOCK_SIZE - (ULONG)StartingVbo;

                PT_DBG_PRINT(PTDBG_TRACE_ROUTINES,
                    ("%s->ExtendingFile success. Filesize = %I64d StartingVbo = %I64d OriginWriteLength = %d NewLength = %d.\n",
                        __FUNCTION__,
                        FileSize,
                        StartingVbo,
                        StreamContext->FileSize,
                        Data->Iopb->Parameters.Write.Length));

                FltSetCallbackDataDirty(Data);

            }
        }
    }
```
这里做了一次记录，然后在`PostWrite`中做了还原。

但是对于NonCached并没有这种还原操作。这导致Data->IoStatus.Infomation=0x10（实际上小于0x10）；进而导致在应用程序执行第二次写入操作时，FileSize变成了0x10。

所以在PreWrite的NonCachedIO中是不是也要做还原呀？

**Comment by wangzhankun** [comment]
下图是我在NonCachedIO的PostWrite中的截图，请问为啥`Write.Length == 0x1000`，而`IoStatus.Information==0x14`呀。实际上也确实是0x14。但是`Write.Length`不是指示文件系统写入多少字节的吗？为啥该值会和IoStatus.Information不一样呢？

我看在CachedIo中倒是`Write.Length == 0x14`。是CachedIo中的参数指示了要写入多少吗？而NonCachedIO中的`Write.Length`参数无意义？
<img width="652" alt="image" src="https://user-images.githubusercontent.com/35724924/175843456-3f372f89-cc5a-4961-8813-1fce84a26bde.png">

**Comment by hkx3upper** [comment]
> > 测试这种情况的话，可以先直接用记事本写入偏移0，大小0x7的数据，然后用自己的测试程序**非缓冲**写入偏移0x200，大小0x120（随便），这样前面的一块原本使用的是流密码的话，那么就出现问题了。 再者说，密文挪用这种方法本身也会出现问题，如果前面一段的数据不对齐，使用密文挪用加密了，之后又**直接**写入一段数据，那么前面的密文挪用也无法正常解密了。 所以这里我考虑的情况还只是应用程序把所有的数据读出，然后修改，再整体写入，这样就没问题了
> 
> 请问你这边说把数据都读出了，代码是在哪里呀？我在Write.c中好像没有找到相关的代码哎。

没，我意思是，把数据读出来可以解决这个问题。

**Comment by hkx3upper** [comment]
> 在`PostWrite`中：
> 
> ```c++
>     if (BooleanFlagOn(Data->Iopb->IrpFlags, IRP_NOCACHE) &&
>         TRUE != StreamContext->LessThanAesBlockSize)
>     {
>         /*
>         * 记录文件的明文大小，小于16个字节的StreamContext->FileSize已经在其他处更新过了，
>         * 这里不能再更新了，因为这里的FileSize已经是16个字节了。
>         */
>         ExEnterCriticalRegionAndAcquireResourceExclusive(StreamContext->Resource);
> 
>         StreamContext->FileSize = ((PFSRTL_ADVANCED_FCB_HEADER)FltObjects->FileObject->FsContext)->FileSize.QuadPart;
> 
>         ExReleaseResourceAndLeaveCriticalRegion(StreamContext->Resource);
>     }
> ```
> 
> 注释说是`小于16个字节的StreamContext->FileSize已经在其他处更新过了`，但是我没有在代码中找到哎。这个应该就是在前两次写入的时候多写入的原因吧？是因为忘了处理了吗？

小于16个字节，分别在SetInfo->EOF和WriteCachedIo时扩展文件大小到16字节。现在应该没有多写的问题了，之前我碰到时，把问题解决了。

**Comment by hkx3upper** [comment]
> ## 执行顺序
> 我发现NonCachedIO和CachedIo在Post执行上有些反直觉。应用程序在指定了`FILE_FLAG_WRITE_THROUGH`时，一次Write过程时这样的：
> 
> 1. PreWrite    CachedIO
> 2. PreWrite    NonCachedIO
> 3. PostWrite   NonCachedIO
> 4. PostWrite   CachedIO
> 
> 这四步的过程有些反直觉。直觉上应该是执行完PreWrite的CachedIO之后应该立即执行CachedIo的PostWrite才是，但是实际过程与此相反。直觉是，应该是限制性CachedIO的PostWrite再执行NonCachedIO的PostWrite，但是实际上也与此相反。
> 
> ## 写入长度还原
> 在针对`FileSize<AES_BLOCK_SIZE`的文件大小上有做一次还原的操作，
> 
> ```c++
>     if (!NonCachedIo)
>     {
>         /*
>         * 16个字节以内扩展文件大小，还有一处在PreSetInfo，按道理应该是if (!PagingIo)，但
>         * NonCachedIo要求Length > SectorSize，所以if (!NonCachedIo)就行。
>         */
> 
>         if (FileSize < AES_BLOCK_SIZE)
>         {
>             /*
>             * FSD的Write会帮我们扩展文件大小，可以在FastFat的Write中搜索ExtendingFile
>             */
>             if (StartingVbo + Data->Iopb->Parameters.Write.Length < AES_BLOCK_SIZE)
>             {
>                 SwapBufferContext->OriginalLength = Data->Iopb->Parameters.Write.Length;
> 
>                 ExEnterCriticalRegionAndAcquireResourceExclusive(StreamContext->Resource);
> 
>                 StreamContext->FileSize = StartingVbo + Data->Iopb->Parameters.Write.Length;
>                 StreamContext->LessThanAesBlockSize = TRUE;
> 
>                 ExReleaseResourceAndLeaveCriticalRegion(StreamContext->Resource);
> 
>                 Data->Iopb->Parameters.Write.Length = AES_BLOCK_SIZE - (ULONG)StartingVbo;
> 
>                 PT_DBG_PRINT(PTDBG_TRACE_ROUTINES,
>                     ("%s->ExtendingFile success. Filesize = %I64d StartingVbo = %I64d OriginWriteLength = %d NewLength = %d.\n",
>                         __FUNCTION__,
>                         FileSize,
>                         StartingVbo,
>                         StreamContext->FileSize,
>                         Data->Iopb->Parameters.Write.Length));
> 
>                 FltSetCallbackDataDirty(Data);
> 
>             }
>         }
>     }
> ```
> 
> 这里做了一次记录，然后在`PostWrite`中做了还原。
> 
> 但是对于NonCached并没有这种还原操作。这导致Data->IoStatus.Infomation=0x10（实际上小于0x10）；进而导致在应用程序执行第二次写入操作时，FileSize变成了0x10。
> 
> 所以在PreWrite的NonCachedIO中是不是也要做还原呀？

![19](https://user-images.githubusercontent.com/41336794/183878399-00488a74-412c-4157-a1fa-246fd4f895c6.jpg)
你看我画的这个图，这四步没问题吧？它本身是一种递归的方式，先PreCachedIo，再PreNonCachedIo......

扩展文件大小不处理NonCachedIo，通常情况下，都是在CachedIo或者SetInformation时扩展文件大小，然后NonCachedIo写入，由文件系统驱动根据之前的文件大小截断数据。

数据不是小于0x10，因为AES要求块大小对齐，所以加密后的数据就是0x10大小。

**Comment by hkx3upper** [comment]
> 下图是我在NonCachedIO的PostWrite中的截图，请问为啥`Write.Length == 0x1000`，而`IoStatus.Information==0x14`呀。实际上也确实是0x14。但是`Write.Length`不是指示文件系统写入多少字节的吗？为啥该值会和IoStatus.Information不一样呢？
> 
> 我看在CachedIo中倒是`Write.Length == 0x14`。是CachedIo中的参数指示了要写入多少吗？而NonCachedIO中的`Write.Length`参数无意义？ <img alt="image" width="652" src="https://user-images.githubusercontent.com/35724924/175843456-3f372f89-cc5a-4961-8813-1fce84a26bde.png">

是的，还是上面说的都是在CachedIo或者SetInformation时扩展文件大小，然后NonCachedIo写入，由文件系统驱动根据之前的文件大小截断数据，IoStatus.Information返回的就是真正写入磁盘的数据大小。

**Comment by hkx3upper** [comment]
要是有空看毛德操的Windows内核情景分析的文件系统部分，看完以后看Fastfat的Create，Read，Write，SetInformation。这些问题的答案都在书和代码里。抽两个周的时间看看，所有问题都清晰了。 @wangzhankun

**Comment by wangzhankun** [comment]
关于这一部分我前段时间改好了。
我参考了 FastFat的代码。关于FileSize的修改应该这样写。原来是把这一部分代码写到了
if(NonCachedIO)里面了。这是不对的。无论是否是CachedIO,，都应该修改FileSize.
![image](https://user-images.githubusercontent.com/35724924/185630714-80d6adfe-a4b9-49e2-98bc-98f8e0513d2d.png)

但是我现在的代码跟你原来的代码设计差距太大了。包括加解密的逻辑，我取消了密文挪用等设计。
同时我在自己做测试的过程中也发现了很多其它的bug，没有添加issue。为了解决这些bug，很多逻辑和代码都改了非常多。

**Comment by wangzhankun** [comment]
在图中的177行那里记录了原始文件大小。在PostWrite中需要判断 `Data`中的 Status，如果发现下层失败了，就需要还原 FileSize

**Comment by hkx3upper** [comment]
ok，如果方便的话可以上传到wangzhankun分支
