### ISSUE TITLE
close前刷新缓冲导致程序卡死

### ISSUE THREAD

**Issue by wangzhankun** [hkx3upper/FOKS-TROT#26]
测试程序如下：
```cpp
#include <iostream>
#include <string>
#include <fstream>
#include <windows.h>

using namespace std;

const std::string root_dir("C:\\Users\\xxxx\\Desktop\\testdata\\");

void create_little_and_big_file()
{
    string file_name = root_dir + "little_and_big.txt";
    std::ofstream ofs(file_name);
    for (int i = 0; i < 5; ++i) 
    {
        ofs << "hello world\n";
        ofs.flush();
        system("pause");
    }
    for (int i = 0; i < 100; ++i) // 1.2KB
    {
        ofs << "hello world\n";
    }
    std::cout << "Press any key to close the file ..." << std::endl;
    system("pause");
    ofs.close();
}

int main(int argc, char **argv)
{
    cout << "create little and big file ..." << endl;
    create_little_and_big_file();
    return 0;
}

```

当测试程序执行到`ofs.close()`时，minifilter会转入执行刷新缓冲的操作。调用过程如下`PostCloseOperation-->PocFlushOriginalCache-->FltFlushBuffers`。当minifilter执行`FltFlushBuffers`之后会产生一个`IRP_MJ_WRITE`的操作并进入到minifilter的`PreWrite`和`PostWrite`过程。检查发现，当`PreWrite`和`PostWrite`正常执行成功之后，应用程序卡死，minifilter也是卡在了`FltFlushBuffers`。该卡死并不影响其它过程，仅仅是当前进程阻塞。

**Comment by wangzhankun** [comment]
我有个疑问是是否真的有必要在关闭前刷新缓冲呢？

**Comment by hkx3upper** [comment]
其实不太应该，没办法的办法，要是这里刷新缓冲不死锁，那么写入文件尾的Write函数也会导致死锁......

**Comment by wangzhankun** [comment]
你是指`PocAppendEncTailerToFile`写入文件尾吗？实际测试发现并没有出现死锁的情况，如果把上一行的`PocFlushOriginalCache`注释掉之后。

我是不太理解`PocFlushOriginalCache`的意义。因为如果用户发送了IRP_MJ_CLOSE之后，那么就应该是关闭文件了，无论缓冲区中是否还有未刷入硬盘的数据都不应该由驱动去做这个事情。应当由应用程序去实现。比如示例程序中的`ofs.close()`实际上会调用刷入缓冲的函数之后再关闭文件。

**Comment by hkx3upper** [comment]
Close不是用户发送的，ofs.close()不会调用Close，Close是IO管理器调用的，我测试的一些情况加上这个刷新缓冲确实可以减轻死锁

**Comment by wangzhankun** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    同学，你好。请问你方便加一下QQ之类的吗？我在github上看到了你的QQ邮箱。方便之后怼FOKS-TROT的管理进行快速讨论。当然bug等我也会直接在GitHub上开issue。当然，不方便的话也没关系，用邮箱交流也是可以的。
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年5月18日 18:25
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [hkx3upper/FOKS-TROT] close前刷新缓冲导致程序卡死 (Issue #26)
        
      
    
  
  

Close不是用户发送的，ofs.close()不会调用Close，Close是IO管理器调用的，我测试的一些情况加上这个刷新缓冲确实可以减轻死锁

**Comment by hkx3upper** [comment]
就在这吧，正好记录一下问题嘛

**Comment by hkx3upper** [comment]
主要是我之后应该没太有时间继续搞透明加解密了，我也不知道之后去工作了搞啥东西

**Comment by hkx3upper** [comment]
这个代码修改的地方太多了，还是回滚到昨天之前吧，等会我出一个代码规范，咱们俩一起谈论一下

**Comment by wangzhankun** [comment]
> Close不是用户发送的，ofs.close()不会调用Close，Close是IO管理器调用的，我测试的一些情况加上这个刷新缓冲确实可以减轻死锁

我不太明白你这里所说的死锁是指什么呀？就我看`PocFlushOriginalCache`函数刷新的应该也是当前进程管理的FileObject对应的缓冲吧？在`PreClose`里面做了一次`SectionObjectPointers`的还原，那么此时机密进程与非机密进程都是指向同一个密文缓冲区。因此这里刷新的应当是密文缓冲吧？那么不会导致当前进程的修改的数据丢失吗？所以我一直搞不太懂这里刷新缓冲的意义。

**Comment by wangzhankun** [comment]
就我很奇怪的是刷新原始缓存这一步，为啥是在postclose里面做的而不是在preclose里面完成呢？

**Comment by wangzhankun** [comment]
同学，请问刷新缓存和添加文件标识尾要在PostClose中做而不是PreClose中做的考量是什么呀？

**Comment by hkx3upper** [comment]
这个问题应该已经解决了，代码还没上传。
PreClose和PostClose好像没差别，我刚开始写代码的时候选的PostClose，那时候有些地方还没理解透，应该没差别。

**Comment by hkx3upper** [comment]
此问题已解决
