### ISSUE TITLE
添加机密文件夹的设计

### ISSUE THREAD

**Issue by wangzhankun** [hkx3upper/FOKS-TROT#27]
目前的驱动设计是在全盘进行加解密，在测试阶段可能会由于驱动的错误导致某些文件被错误加密而出现无法正常打开的情况，因此我添加了机密文件夹的设计。透明加解密被限制在机密文件夹这一层级。请问原作者是否同意把这一设计引入呢？如果可以的话，我就把该设计引入进来。当然目前还是一个比较粗糙的版本。

**Comment by hkx3upper** [comment]
可以的，这个还是很好的，不过要不你还是拉一下最新的版本然后再修改一下吧，昨天我更过新。
话说老哥你一直都在搞透明加解密的吗，你这测试修复和更新的频率这么高的吗？

**Comment by wangzhankun** [comment]
导师安排的任务，所以一直在搞

**Comment by hkx3upper** [comment]
哦哦哦，我给你个contributer吧，这样你自己提交就行了

**Comment by wangzhankun** [comment]
已完成
