### ISSUE TITLE
一次性读取的内存空间不足问题

### ISSUE THREAD

**Issue by wangzhankun** [hkx3upper/FOKS-TROT#35]
在`PocPostReadDecrypt`，和`PocPreWriteOperation`都是一次性分配全部的空间，但是当数据大小很大的时候不是很容易就出现内存不够的情况吗？

我看`PocPostReadDecrypt`的注释中说

>             /*
>           * 当文件大于一个块，Cache Manager将数据分多次读入缓冲，或者其他以NonCachedIo形式
>          * 最后一次读的数据小于一个块的情况下，现在在倒数第二个块做一下处理
>        */

似乎是分批多次读入的。但是我看实际代码还是一次性分配全部的空间哎。

因此Write.c和Read.c中的加解密是要写成分批读写的代码吧？还是说目前的代码就是分批读写的呢？

**Comment by hkx3upper** [comment]
不用，ntfs文件系统设置的Write.Length是ULONG，而且一次的读写IRP也不可能将数据分多次处理，你看SwapBuffers都是一次处理。PocPostReadDecrypt那里是处理的一种特殊情况，
