### ISSUE TITLE
手动加解密独占

### ISSUE THREAD

**Issue by wangzhankun** [hkx3upper/FOKS-TROT#36]
手动加解密时，`FltCreateFileEx`似乎并不能独占打开，可能会导致潜在的数据丢失。
## bug复现
1. 用非机密进程notepad打开测试文档，写入若干字节并保存，但是不关闭
2. 使用PocUserPannel对该文档进行特权加密，加密成功
3. 关闭notepad。使用机密进程notepad++打开该文档，会出现两种情况，一是可能会看到乱码（小概率），二是notepad写入的数据丢失了。

## 补充说明
我这里只是测试了一种情况。关于对要进行特权加密和特权解密的文档可能处于各种情况，都有可能会对文件造成损坏。对于各种打开、写入等的情况的处理太过复杂。

我的建议是，PocUserPannel或者驱动首先对要进行特权加密/特权解密的文件进行扫描，如果发现该文档被某个进程持有，那么就不能进行加解密。

另外如果驱动正在对文件进行特权加解密，那么在PreCreate中就拒绝所有的尝试打开操作，直至文件加密/解密完成。

关于这个功能，你有什么建议吗？

**Comment by wangzhankun** [comment]
你说的这个自动加密是处于机密文件夹下、机密拓展名才会有的。我指的是不会自动加密的情况。

**Comment by hkx3upper** [comment]
出现的两种情况都是针对一个未加密的文件？

**Comment by wangzhankun** [comment]
对的。都是不会自动加密的。因为手动加解密的功能本身就是针对不会被自动加密的文件嘛，所以我讨论的都是指不会自动加密的文件。

极小概率的机密进程打开特权加密的文件是乱码也不是重复加密导致的。因为我只解密了一次，就能正常看到明文了。

**Comment by hkx3upper** [comment]
出现乱码是因为它不在驱动的控制范围内，StreamContext引用为0了，被自动清除掉了。

**Comment by wangzhankun** [comment]
> 

我这里的bug复现的第3步中，数据丢失也只是一种情况，也有可能数据不丢失。

因为如果在特权加解密的过程中不独占的话，没办法知晓其它进程对该文件做的修改。再比如说，驱动在对文件加密过程写入的时候，A进程强制刷新缓存，这不就会把加密的数据给覆盖掉吗？这也是一种可能导致错误的情况。

就是多个进程对同一份文档进行读写操作的话，各种读写序列和缓存管理太复杂了。所以我建议是以独占的形式进行加解密。

**Comment by hkx3upper** [comment]
写入数据丢失的情况，该文件之前被加密过吗？是否是非授权进程对一个已加密过的文件写入数据？

**Comment by hkx3upper** [comment]
独占没问题，这里其实可以有SHARE_READ，只要没有SHARE_WRITE就行吧。
文件系统驱动本身也会做缓冲一致性的处理，所以我没觉得是缓冲的问题。

**Comment by wangzhankun** [comment]
但是`FltCreateFileEx`不能够进行独占哎。我使用notepad打开测试文件的情况下，进行特权加密，仍然能够正常打开文件并进行加密。所以得采用其它的方法保证独占。

> 独占没问题，这里其实可以有SHARE_READ，只要没有SHARE_WRITE就行吧。 文件系统驱动本身也会做缓冲一致性的处理，所以我没觉得是缓冲的问题。

**Comment by wangzhankun** [comment]
> 写入数据丢失的情况，该文件之前被加密过吗？是否是非授权进程对一个已加密过的文件写入数据？

## bug复现
1. 用非机密进程notepad打开测试文档（未加密，明文，没有文件标识尾），写入若干字节并保存，但是不关闭
2. 使用PocUserPannel对该文档进行特权加密，加密成功
3. 关闭notepad。使用机密进程notepad++打开该文档，会出现两种情况，一是可能会看到乱码（小概率），二是notepad写入的数据丢失了，也有可能notepad的数据被正常写入了。

**Comment by hkx3upper** [comment]
`但是FltCreateFileEx不能够进行独占哎。我使用notepad打开测试文件的情况下，进行特权加密，仍然能够正常打开文件并进行加密。所以得采用其它的方法保证独占。`
当然是独占了。你notepad打开文件，这个过程很短暂的，它读出来以后，就会释放掉这个FileObject，你看到的数据都是在notepad进程的内存里的。
然后现在你独占特权加密，现在没有任何其他进程读写文件，独占成功，然后很快你就写完，释放FileObject了，然后其他进程就可以读文件了。
独占是一个很短暂的过程。

**Comment by hkx3upper** [comment]
乱码的情况既然能够正常解密，说明文件还是加密成功了。乱码的情况能看到标识尾吗？
写入的数据丢失了，你重启一下，不开驱动，是否能看到已加密的文件？

**Comment by hkx3upper** [comment]
其实和你关不关闭这个进程没有一点的关系

**Comment by hkx3upper** [comment]
那个FltCreateFile加一个标识FILE_SYNCHRONOUS_IO_NONALERT，
另外，这个问题其实不难解决，你下个断点，看一下特权加密读取出来的明文数据是什么。 @wangzhankun

**Comment by hkx3upper** [comment]
乱码和空白是因为read_buffer没清零，FltReadFileEx没有读出数据，返回STATUS_PENDING，加密了read_buffer的脏数据。
添加FILE_SYNCHRONOUS_IO_NONALERT标识就解决这个问题了。 @wangzhankun

**Comment by wangzhankun** [comment]
> 乱码和空白是因为read_buffer没清零，FltReadFileEx没有读出数据，返回STATUS_PENDING，加密了read_buffer的脏数据。 添加FILE_SYNCHRONOUS_IO_NONALERT标识就解决这个问题了。 @wangzhankun

加上这个标志位之后，先前提到的读写序列问题导致的乱码解决了。但是我又测试出来一个乱码问题。我想办法复现一下。

**Comment by wangzhankun** [comment]
> > 乱码和空白是因为read_buffer没清零，FltReadFileEx没有读出数据，返回STATUS_PENDING，加密了read_buffer的脏数据。 添加FILE_SYNCHRONOUS_IO_NONALERT标识就解决这个问题了。 @wangzhankun
> 
> 加上这个标志位之后，先前提到的读写序列问题导致的乱码解决了。但是我又测试出来一个乱码问题。我想办法复现一下。

不对，还是这个问题。只是乱码的情况很少见。加上标志位还是同样的bug。还是一样的操作。只是有时候是正确的，有时候就是错误的。

## bug复现
1. 用非机密进程notepad打开测试文档（未加密，明文，没有文件标识尾），写入若干字节并保存，但是不关闭
2. 使用PocUserPannel对该文档进行特权加密，加密成功
3. 关闭notepad。使用机密进程notepad++打开该文档，会出现两种情况，一是可能会看到乱码（小概率），二是notepad写入的数据丢失了，也有可能notepad的数据被正常写入了。

**Comment by hkx3upper** [comment]
解决了，
![image](https://user-images.githubusercontent.com/41336794/175004766-ab9e3fa2-a34b-4d8b-b1af-71f91b4d276a.png)
注释掉这个 @wangzhankun

**Comment by wangzhankun** [comment]
这边注释掉之后，其它与其相关的逻辑是不是也得注释掉呀？比如说`PocPreCreate`函数中的相关代码。

![image](https://user-images.githubusercontent.com/35724924/175025226-b312ec40-7e86-4b1c-9541-c87e3a792b35.png)

**Comment by wangzhankun** [comment]
> 这边注释掉之后，其它与其相关的逻辑是不是也得注释掉呀？比如说`PocPreCreate`函数中的相关代码。
> 
> ![image](https://user-images.githubusercontent.com/35724924/175025226-b312ec40-7e86-4b1c-9541-c87e3a792b35.png)



这一部分的逻辑要不你先处理一下吧？你那边处理好了我在我这边拉去合并一下。测试好之后再合并回来。

**Comment by hkx3upper** [comment]
![image](https://user-images.githubusercontent.com/41336794/175186631-92f6e6b9-904a-4cd8-8a74-565a98c8238f.png)
放在这里吧，Create那里就不用改了

**Comment by wangzhankun** [comment]
> ![image](https://user-images.githubusercontent.com/41336794/175186631-92f6e6b9-904a-4cd8-8a74-565a98c8238f.png) 放在这里吧，Create那里就不用改了

放在这里也不行，同样会有乱码的问题。

**Comment by wangzhankun** [comment]
类似 #34
